import { Box } from '@mui/joy'
import Head from 'next/head'

export default function Layout(props: { children: any }) {
    return (
        <>
            <Head>
                <title>Daily Arxiv</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                sx={{
                    p: { xs: '0 1rem', sm: '0 2rem' },
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                }}>
                {props.children}
            </Box>
        </>
    )
}