import type { NextPage } from 'next'
import Head from 'next/head'
import CollapseCheckList from '../components/categoryTree/categorytree'
import CalendarComponent from '../components/calendar/calendar'
import { fetchArchive, ListCategoryHeading, makeArxivDatabase, queryToUrl } from '../scripts/apiTools'
import styles from '../styles/Home.module.css'
import { FormProvider, useForm } from 'react-hook-form'
import { Button, Collapse, List, ListItemButton, ListItemText } from '@mui/material'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { useAppContext } from './_app'
import { ExpandLess, ExpandMore } from '@mui/icons-material'
import { useState } from 'react'
import CategoryForm from '../components/categoryTree/categoryForm'

const Home: NextPage = () => {
	const router = useRouter();
	const dbobj: ListCategoryHeading[] = makeArxivDatabase();
	const defaultValues = { categories: dbobj }
	const methods = useForm({ defaultValues })
	const appContext = useAppContext();

	const onSubmit = async (data: any) => {
		console.log(data);
		const url = queryToUrl('all:electron', data.datepicker);
		console.log(url);
		const response = await fetchArchive(url);
		console.log(response);
		appContext.results = response as any[];
		router.push('/results');
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Daily Arxiv</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<FormProvider {...methods}>
					<div className={styles.welcome}>
						<h1 className={styles.title}>
							Daily  <Link href="/">arXiv</Link>
						</h1>

						<p className={styles.description}>
							Get started by choosing a date below.
						</p>

						<CalendarComponent />
					</div>

					<div className={styles.categoryTree}>
						<List
							sx={{ width: '100%', bgcolor: 'background.paper' }}>
							{dbobj.map((section, i) => {
								return (
									<CategoryForm key={i} section={section} />
								)
							})}
						</List>
					</div>

					<Button
						onClick={methods.handleSubmit(onSubmit)}
						variant="contained">Submit</Button>
				</FormProvider>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					by Justin Edwards
				</a>
			</footer>
		</div>
	)
}

export default Home