import type { NextPage } from 'next'
import Head from 'next/head'
import CalendarComponent from '../components/calendar/calendar'
import { fetchArchive, queryToUrl, ArxivCategories } from '../scripts/apiTools'
import styles from '../styles/Home.module.css'
import { FormProvider, useForm } from 'react-hook-form'
import { Button, List } from '@mui/material'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { useAppContext } from './_app'
import CategoryForm from '../components/categoryTree/categoryForm'

const Home: NextPage = () => {
	const router = useRouter();
	const defaultValues = { categories: ArxivCategories }
	const methods = useForm({ defaultValues })
	const appContext = useAppContext();

	const onSubmit = async (data: any) => {
		console.log(data);
		const url = queryToUrl('cat:astro-ph.GA+OR+cat:math.AT+OR+cat:math.CT', data.datepicker);
		console.log(url);
		const response = await fetchArchive(url);
		// console.log(response);
		appContext.results = response as any[];
		await router.push('/results');
	}

	return (
		<div className={styles.scrollParent}>
			<div className={styles.container}>
				<Head>
					<title>Daily Arxiv</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<FormProvider {...methods}>
					<div className={styles.welcome}>
						<h1 className={styles.title}>
							Daily  <Link href="/">arXiv</Link>
						</h1>

						<p className={styles.description}>
							Get started by choosing a date below.
						</p>

						<CalendarComponent />
					</div>

					<div className={styles.categoryTree}>
						<List
							sx={{ width: '100%', bgcolor: 'background.paper' }}>
							{ArxivCategories.map((category, i) => {
								return <CategoryForm key={i} idx={i} section={category} />
							})}
						</List>

						<Button
							onClick={methods.handleSubmit(onSubmit)}
							variant="contained">Submit</Button>
					</div>
				</FormProvider>

				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						by Justin Edwards
					</a>
				</footer>
			</div>
		</div>
	)
}

export default Home