import type { NextPage } from 'next'
import Head from 'next/head'
import CalendarComponent from '../components/calendar/calendar'
import { fetchArchive, queryToUrl, ArxivCategories, buildQuery } from '../scripts/apiTools'
import styles from '../styles/Home.module.css'
import { FormProvider, useForm } from 'react-hook-form'
import { Button } from '@mui/material'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { useAppContext } from './_app'
import CategoryFormField from '../components/categoryForm/categoryFormField'

type CategoryForm = {
	categories: ArchiveHeader[]
	datepicker: Date
}

const Home: NextPage = () => {
	const router = useRouter();
	const defaultValues = { categories: ArxivCategories }
	const methods = useForm<CategoryForm>({ defaultValues })
	const appContext = useAppContext();

	const onSubmit = async (data: CategoryForm) => {
		const query = buildQuery(data.categories);
		const url = queryToUrl(query, data.datepicker);
		console.log(url);
		const response = await fetchArchive(url);
		appContext.results = response as ArchiveResult[];
		await router.push('/results');
	}

	return (
		<div className={styles.scrollParent}>
			<div className={styles.container}>
				<Head>
					<title>Daily Arxiv</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<FormProvider {...methods}>
					<div className={styles.welcome}>
						<h1 className={styles.title}>
							Daily  <Link href="/">arXiv</Link>
						</h1>

						<p className={styles.description}>
							Get started by choosing a date below.
						</p>

						<CalendarComponent />
					</div>

					<div className={styles.categoryTree}>
						<CategoryFormField />

						<Button
							style={{ marginTop: '4rem' }}
							onClick={methods.handleSubmit(onSubmit)}
							variant="contained">Search</Button>
					</div>
				</FormProvider>
			</div>
		</div>
	)
}

export default Home